

-- =============================================================
-- 1. ESTRUTURA E MODELAGEM DE DADOS: CRIAÇÃO DAS TABELAS (DDL)
-- =============================================================

-- Criar tabela de Catálogo de Produtos
CREATE TABLE produto (
    id_produto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_produto VARCHAR2(80) NOT NULL,
    preco_produto NUMBER(7,2) NOT NULL,
    categoria_produto VARCHAR2(50) NOT NULL
);

-- Criar tabela de Fornecedores Homologados
CREATE TABLE fornecedor (
    id_fornecedor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_fornecedor VARCHAR2(50) NOT NULL,
    cnpj_fornecedor VARCHAR2(20),
    celular_fornecedor VARCHAR2(20),
    email_fornecedor VARCHAR2(50)
);

-- Criar tabela de Controle Geral de Estoque
CREATE TABLE estoque (
    id_estoque NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_produto_estoque VARCHAR2(80) NOT NULL,
    data_ultima_entrada DATE NOT NULL,
    data_ultima_saida DATE NOT NULL
);

-- Criar tabela de Clientes (Pessoas Físicas e Jurídicas)
CREATE TABLE cliente (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cliente VARCHAR2(50) NOT NULL,
    sexo_cliente CHAR(1) NOT NULL,
    cpf_cliente VARCHAR2(20) NOT NULL,
    celular_cliente VARCHAR2(20),
    email_cliente VARCHAR2(50) NOT NULL
);

-- Criar tabela de Pedidos Associados
CREATE TABLE pedido (
    id_pedido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_pedido DATE NOT NULL,
    quantidade_pedido NUMBER NOT NULL,
    fk_id_cliente NUMBER,
    fk_id_produto NUMBER,
    FOREIGN KEY (fk_id_cliente) REFERENCES cliente (id_cliente),
    FOREIGN KEY (fk_id_produto) REFERENCES produto (id_produto)
);

-- Criar tabela de Fluxo de Pagamentos Recebidos
CREATE TABLE pagamento (
    id_pagamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor_total_pagamento NUMBER(10,2) NOT NULL,
    data_pagamento DATE NOT NULL,
    metodo_pagamento VARCHAR2(20) NOT NULL,
    fk_id_pedido NUMBER,
    FOREIGN KEY (fk_id_pedido) REFERENCES pedido (id_pedido)
);

-- Tabela Associativa: Relacionamento Muitos-para-Muitos (N:N) Produto-Fornecedor
CREATE TABLE prod_fornecedor (
    fk_id_produto NUMBER,
    fk_id_fornecedor NUMBER,
    FOREIGN KEY (fk_id_fornecedor) REFERENCES fornecedor (id_fornecedor),
    FOREIGN KEY (fk_id_produto) REFERENCES produto (id_produto)
);

-- Tabela Associativa: Relacionamento Muitos-para-Muitos (N:N) Pagamento-Cliente
CREATE TABLE pagamento_cliente (
    fk_id_cliente NUMBER,
    fk_id_pagamento NUMBER,
    FOREIGN KEY (fk_id_cliente) REFERENCES cliente (id_cliente),
    FOREIGN KEY (fk_id_pagamento) REFERENCES pagamento (id_pagamento)
);

-- Tabela Associativa: Relacionamento Muitos-para-Muitos (N:N) Armazenamento-Estoque
CREATE TABLE armazenamento_estoque (
    fk_id_produto NUMBER,
    fk_id_estoque NUMBER,
    FOREIGN KEY (fk_id_produto) REFERENCES produto (id_produto),
    FOREIGN KEY (fk_id_estoque) REFERENCES estoque (id_estoque)
);


-- ================================================================
-- 2. POPULAÇÃO DA BASE DE DADOS: INSERÇÃO DE DADOS DE TESTE (DML)
-- ================================================================

-- Inserção de Produtos
INSERT INTO produto (nome_produto, preco_produto, categoria_produto) VALUES 
('Aplicativos Móveis', 500.00, 'Aplicativos');
INSERT INTO produto (nome_produto, preco_produto, categoria_produto) VALUES 
('Software de Gestão de Despesas e Viagens Corporativas', 850.00, 'Software de Gestão');
INSERT INTO produto (nome_produto, preco_produto, categoria_produto) VALUES 
('Software de Central de Atendimento', 950.00, 'Central de Atendimento');
INSERT INTO produto (nome_produto, preco_produto, categoria_produto) VALUES 
('Software de Gerenciamento de Relacionamento com o Cliente', 900.00, 'Relacionamento');

-- Inserção de Fornecedores
INSERT INTO fornecedor (nome_fornecedor, cnpj_fornecedor, celular_fornecedor, email_fornecedor) VALUES 
('Aplicativo','04.009.999/0001-10','(11) 91020-3040','Aplicativo@gmail.com');
INSERT INTO fornecedor (nome_fornecedor, cnpj_fornecedor, celular_fornecedor, email_fornecedor) VALUES 
('Software Gestão','66.057.014/0001-20','(11) 92030-4050','Software_gestao@outlook.com');
INSERT INTO fornecedor (nome_fornecedor, cnpj_fornecedor, celular_fornecedor, email_fornecedor) VALUES 
('Relacionamento','13.014.115/0001-30','(11) 94050-6070','Relacionamento@yahoo.com');
INSERT INTO fornecedor (nome_fornecedor, cnpj_fornecedor, celular_fornecedor, email_fornecedor) VALUES 
('Central','10.406.845/0001-80','(13) 98070-9010','Central@gmail.com');

-- Inserção no Estoque
INSERT INTO estoque (nome_produto_estoque, data_ultima_entrada, data_ultima_saida) VALUES 
('Aplicativos Móveis', DATE '2026-03-24', DATE '2026-04-24');
INSERT INTO estoque (nome_produto_estoque, data_ultima_entrada, data_ultima_saida) VALUES 
('Software de Gestão de Despesas e Viagens Corporativas', DATE '2026-04-26', DATE '2026-06-30');
INSERT INTO estoque (nome_produto_estoque, data_ultima_entrada, data_ultima_saida) VALUES 
('Software de Central de Atendimento', DATE '2026-03-05', DATE '2026-05-28');
INSERT INTO estoque (nome_produto_estoque, data_ultima_entrada, data_ultima_saida) VALUES 
('Software de Gerenciamento de Relacionamento com o Cliente', DATE '2026-05-10', DATE '2026-05-31');

-- Inserção no cadastro de Clientes
INSERT INTO cliente (nome_cliente, sexo_cliente, cpf_cliente, celular_cliente, email_cliente) VALUES 
('Lucas','M','481.552.748-29','(11) 98105-7555','lucas@gmail.com');
INSERT INTO cliente (nome_cliente, sexo_cliente, cpf_cliente, celular_cliente, email_cliente) VALUES 
('Amanda','F','482.098.472-98','(11) 92834-7334','amanda@gmail.com');
INSERT INTO cliente (nome_cliente, sexo_cliente, cpf_cliente, celular_cliente, email_cliente) VALUES 
('Maria','F','428.304.392-56','(11) 92384-7203','maria@gmail.com');
INSERT INTO cliente (nome_cliente, sexo_cliente, cpf_cliente, celular_cliente, email_cliente) VALUES 
('Carlos','M','382.932.843-12','(11) 92837-4283','carlos@gmail.com');

-- Inserção no fluxo de Pedidos
INSERT INTO pedido (data_pedido, quantidade_pedido, fk_id_cliente, fk_id_produto) VALUES 
(DATE '2026-03-24',1,1,1);
INSERT INTO pedido (data_pedido, quantidade_pedido, fk_id_cliente, fk_id_produto) VALUES 
(DATE '2026-04-30',1,2,2);
INSERT INTO pedido (data_pedido, quantidade_pedido, fk_id_cliente, fk_id_produto) VALUES 
(DATE '2026-05-12',1,3,3);
INSERT INTO pedido (data_pedido, quantidade_pedido, fk_id_cliente, fk_id_produto) VALUES 
(DATE '2026-05-31',1,4,4);

-- Inserção no fluxo de fechamento de Pagamentos
INSERT INTO pagamento (valor_total_pagamento, data_pagamento, metodo_pagamento, fk_id_pedido) VALUES 
(500, DATE '2026-03-24','Pix',1);
INSERT INTO pagamento (valor_total_pagamento, data_pagamento, metodo_pagamento, fk_id_pedido) VALUES 
(850, DATE '2026-04-30','Credito',2);
INSERT INTO pagamento (valor_total_pagamento, data_pagamento, metodo_pagamento, fk_id_pedido) VALUES 
(950, DATE '2026-05-12','Debito',3);
INSERT INTO pagamento (valor_total_pagamento, data_pagamento, metodo_pagamento, fk_id_pedido) VALUES 
(900, DATE '2026-05-31','Dinheiro',4);
